import { INITIAL_BADGE_STATE, type BadgeState } from "../types";

export type BadgePreset = {
  id: string;
  name: string;
  description: string;
  tags: string[];
  family: string;
  archetype: string;
  size: string;
  state: Partial<BadgeState>;
};

type BadgeTheme = {
  id: string;
  name: string;
  color: string;
  textColor: string;
  dotColor: string;
  shadowColor: string;
  gradientStart: string;
  gradientEnd: string;
};

type BadgeArchetype = {
  id: string;
  name: string;
  label: string;
  description: string;
  variant: BadgeState["variant"];
  shape: BadgeState["shape"];
  iconName: BadgeState["iconName"];
  iconPosition: BadgeState["iconPosition"];
  showIcon: boolean;
  showDot: boolean;
  dismissible: boolean;
  interactive: boolean;
  hoverScale: number;
  clickRipple: boolean;
  gradientEnabled: boolean;
  dropShadow: boolean;
  use3D: boolean;
  tiltEnabled: boolean;
  icon3DEnabled: boolean;
  icon3DGeometry: BadgeState["icon3DGeometry"];
  icon3DSpinSpeed: number;
  ariaRole: BadgeState["ariaRole"];
  ariaLive: BadgeState["ariaLive"];
  tags: string[];
};

type BadgeSizeProfile = {
  id: string;
  name: string;
  badgeSize: BadgeState["size"];
  paddingX: number;
  paddingY: number;
  fontSize: number;
  borderRadius: number;
  borderWidth: number;
  iconGap: number;
  iconSize: number;
  shadowBlur: number;
  depth: number;
  tiltMax: number;
  glareOpacity: number;
  labelCount: string;
};

const BADGE_THEMES: BadgeTheme[] = [
  {
    id: "slate",
    name: "Slate",
    color: "#334155",
    textColor: "#f8fafc",
    dotColor: "#94a3b8",
    shadowColor: "rgba(15, 23, 42, 0.24)",
    gradientStart: "#475569",
    gradientEnd: "#0f172a",
  },
  {
    id: "cobalt",
    name: "Cobalt",
    color: "#2563eb",
    textColor: "#eff6ff",
    dotColor: "#93c5fd",
    shadowColor: "rgba(37, 99, 235, 0.28)",
    gradientStart: "#60a5fa",
    gradientEnd: "#1d4ed8",
  },
  {
    id: "emerald",
    name: "Emerald",
    color: "#059669",
    textColor: "#ecfdf5",
    dotColor: "#6ee7b7",
    shadowColor: "rgba(5, 150, 105, 0.28)",
    gradientStart: "#34d399",
    gradientEnd: "#047857",
  },
  {
    id: "sunset",
    name: "Sunset",
    color: "#ea580c",
    textColor: "#fff7ed",
    dotColor: "#fdba74",
    shadowColor: "rgba(234, 88, 12, 0.26)",
    gradientStart: "#fb923c",
    gradientEnd: "#c2410c",
  },
  {
    id: "rose",
    name: "Rose",
    color: "#e11d48",
    textColor: "#fff1f2",
    dotColor: "#fda4af",
    shadowColor: "rgba(225, 29, 72, 0.26)",
    gradientStart: "#fb7185",
    gradientEnd: "#be123c",
  },
  {
    id: "violet",
    name: "Violet",
    color: "#7c3aed",
    textColor: "#f5f3ff",
    dotColor: "#c4b5fd",
    shadowColor: "rgba(124, 58, 237, 0.28)",
    gradientStart: "#a78bfa",
    gradientEnd: "#5b21b6",
  },
  {
    id: "amber",
    name: "Amber",
    color: "#d97706",
    textColor: "#fffbeb",
    dotColor: "#fcd34d",
    shadowColor: "rgba(217, 119, 6, 0.26)",
    gradientStart: "#fbbf24",
    gradientEnd: "#b45309",
  },
  {
    id: "mint",
    name: "Mint",
    color: "#0f766e",
    textColor: "#f0fdfa",
    dotColor: "#5eead4",
    shadowColor: "rgba(15, 118, 110, 0.26)",
    gradientStart: "#2dd4bf",
    gradientEnd: "#115e59",
  },
  {
    id: "arctic",
    name: "Arctic",
    color: "#0ea5e9",
    textColor: "#f8fafc",
    dotColor: "#7dd3fc",
    shadowColor: "rgba(14, 165, 233, 0.24)",
    gradientStart: "#38bdf8",
    gradientEnd: "#0284c7",
  },
  {
    id: "cherry",
    name: "Cherry",
    color: "#be123c",
    textColor: "#fff1f2",
    dotColor: "#fda4af",
    shadowColor: "rgba(190, 18, 60, 0.26)",
    gradientStart: "#fb7185",
    gradientEnd: "#7f1d1d",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    color: "#0f172a",
    textColor: "#e2e8f0",
    dotColor: "#38bdf8",
    shadowColor: "rgba(2, 6, 23, 0.44)",
    gradientStart: "#334155",
    gradientEnd: "#020617",
  },
  {
    id: "indigo",
    name: "Indigo",
    color: "#4338ca",
    textColor: "#eef2ff",
    dotColor: "#a5b4fc",
    shadowColor: "rgba(67, 56, 202, 0.26)",
    gradientStart: "#818cf8",
    gradientEnd: "#312e81",
  },
];

const BADGE_ARCHETYPES: BadgeArchetype[] = [
  {
    id: "calm-new",
    name: "Calm New",
    label: "New Feature",
    description: "Soft product badge with minimal chrome.",
    variant: "solid",
    shape: "pill",
    iconName: "star",
    iconPosition: "left",
    showIcon: false,
    showDot: false,
    dismissible: false,
    interactive: false,
    hoverScale: 1.02,
    clickRipple: false,
    gradientEnabled: false,
    dropShadow: false,
    use3D: false,
    tiltEnabled: false,
    icon3DEnabled: false,
    icon3DGeometry: "sphere",
    icon3DSpinSpeed: 1,
    ariaRole: "status",
    ariaLive: "polite",
    tags: ["calm", "new", "minimal", "product"],
  },
  {
    id: "alert-count",
    name: "Alert Count",
    label: "Alerts",
    description: "High-contrast status badge with icon and count.",
    variant: "outline",
    shape: "rounded",
    iconName: "alert",
    iconPosition: "left",
    showIcon: true,
    showDot: true,
    dismissible: false,
    interactive: true,
    hoverScale: 1.04,
    clickRipple: false,
    gradientEnabled: false,
    dropShadow: false,
    use3D: false,
    tiltEnabled: false,
    icon3DEnabled: false,
    icon3DGeometry: "sphere",
    icon3DSpinSpeed: 1,
    ariaRole: "alert",
    ariaLive: "assertive",
    tags: ["alert", "count", "status", "outline"],
  },
  {
    id: "glass-signal",
    name: "Glass Signal",
    label: "Signal",
    description: "Glass surface with icon-only emphasis.",
    variant: "glass",
    shape: "circle",
    iconName: "star",
    iconPosition: "only",
    showIcon: true,
    showDot: true,
    dismissible: false,
    interactive: true,
    hoverScale: 1.05,
    clickRipple: true,
    gradientEnabled: true,
    dropShadow: true,
    use3D: true,
    tiltEnabled: true,
    icon3DEnabled: true,
    icon3DGeometry: "sphere",
    icon3DSpinSpeed: 1.2,
    ariaRole: "status",
    ariaLive: "polite",
    tags: ["glass", "signal", "icon-only", "premium"],
  },
  {
    id: "neon-status",
    name: "Neon Status",
    label: "Live",
    description: "Glow-heavy live status badge.",
    variant: "solid",
    shape: "pill",
    iconName: "zap",
    iconPosition: "right",
    showIcon: true,
    showDot: true,
    dismissible: false,
    interactive: true,
    hoverScale: 1.06,
    clickRipple: true,
    gradientEnabled: true,
    dropShadow: true,
    use3D: false,
    tiltEnabled: true,
    icon3DEnabled: false,
    icon3DGeometry: "sphere",
    icon3DSpinSpeed: 1,
    ariaRole: "alert",
    ariaLive: "assertive",
    tags: ["neon", "live", "glow", "status"],
  },
  {
    id: "dismissible-tag",
    name: "Dismissible Tag",
    label: "Beta",
    description: "Compact tagged status with dismiss control.",
    variant: "soft",
    shape: "rounded",
    iconName: "check",
    iconPosition: "left",
    showIcon: true,
    showDot: false,
    dismissible: true,
    interactive: true,
    hoverScale: 1.03,
    clickRipple: false,
    gradientEnabled: false,
    dropShadow: false,
    use3D: false,
    tiltEnabled: false,
    icon3DEnabled: false,
    icon3DGeometry: "sphere",
    icon3DSpinSpeed: 1,
    ariaRole: "status",
    ariaLive: "polite",
    tags: ["dismissible", "beta", "soft", "tag"],
  },
  {
    id: "3d-token",
    name: "3D Token",
    label: "Pro",
    description: "Material badge with full hyper effects enabled.",
    variant: "neumorphic",
    shape: "pill",
    iconName: "shield",
    iconPosition: "left",
    showIcon: true,
    showDot: false,
    dismissible: false,
    interactive: true,
    hoverScale: 1.06,
    clickRipple: true,
    gradientEnabled: false,
    dropShadow: true,
    use3D: true,
    tiltEnabled: true,
    icon3DEnabled: true,
    icon3DGeometry: "cube",
    icon3DSpinSpeed: 1.4,
    ariaRole: "status",
    ariaLive: "polite",
    tags: ["3d", "token", "material", "pro"],
  },
  {
    id: "editorial-chip",
    name: "Editorial Chip",
    label: "Read more",
    description: "Refined capsule badge with editorial tone.",
    variant: "ghost",
    shape: "rounded",
    iconName: "star",
    iconPosition: "right",
    showIcon: true,
    showDot: false,
    dismissible: false,
    interactive: false,
    hoverScale: 1.01,
    clickRipple: false,
    gradientEnabled: false,
    dropShadow: false,
    use3D: false,
    tiltEnabled: false,
    icon3DEnabled: false,
    icon3DGeometry: "sphere",
    icon3DSpinSpeed: 1,
    ariaRole: "status",
    ariaLive: "polite",
    tags: ["editorial", "ghost", "chip", "refined"],
  },
  {
    id: "data-pill",
    name: "Data Pill",
    label: "Orders",
    description: "Count-forward badge for analytics surfaces.",
    variant: "solid",
    shape: "pill",
    iconName: "check",
    iconPosition: "right",
    showIcon: true,
    showDot: true,
    dismissible: false,
    interactive: true,
    hoverScale: 1.04,
    clickRipple: true,
    gradientEnabled: false,
    dropShadow: true,
    use3D: false,
    tiltEnabled: false,
    icon3DEnabled: false,
    icon3DGeometry: "sphere",
    icon3DSpinSpeed: 1,
    ariaRole: "status",
    ariaLive: "polite",
    tags: ["data", "analytics", "count", "pill"],
  },
  {
    id: "hero-badge",
    name: "Hero Badge",
    label: "Featured",
    description: "Hero-facing badge with luminous framing.",
    variant: "glass",
    shape: "circle",
    iconName: "bell",
    iconPosition: "only",
    showIcon: true,
    showDot: true,
    dismissible: false,
    interactive: true,
    hoverScale: 1.05,
    clickRipple: true,
    gradientEnabled: true,
    dropShadow: true,
    use3D: true,
    tiltEnabled: true,
    icon3DEnabled: true,
    icon3DGeometry: "torus",
    icon3DSpinSpeed: 1.1,
    ariaRole: "status",
    ariaLive: "polite",
    tags: ["hero", "featured", "glass", "badge"],
  },
  {
    id: "status-dot",
    name: "Status Dot",
    label: "Online",
    description: "Dot-first badge for presence and availability.",
    variant: "soft",
    shape: "rounded",
    iconName: "star",
    iconPosition: "left",
    showIcon: false,
    showDot: true,
    dismissible: false,
    interactive: true,
    hoverScale: 1.02,
    clickRipple: false,
    gradientEnabled: false,
    dropShadow: false,
    use3D: false,
    tiltEnabled: false,
    icon3DEnabled: false,
    icon3DGeometry: "sphere",
    icon3DSpinSpeed: 1,
    ariaRole: "status",
    ariaLive: "polite",
    tags: ["status", "dot", "presence", "soft"],
  },
  {
    id: "pricing-chip",
    name: "Pricing Chip",
    label: "Starting at $12",
    description: "Pricing badge with a crisp product surface.",
    variant: "outline",
    shape: "pill",
    iconName: "shield",
    iconPosition: "left",
    showIcon: true,
    showDot: false,
    dismissible: false,
    interactive: false,
    hoverScale: 1.01,
    clickRipple: false,
    gradientEnabled: false,
    dropShadow: false,
    use3D: false,
    tiltEnabled: false,
    icon3DEnabled: false,
    icon3DGeometry: "sphere",
    icon3DSpinSpeed: 1,
    ariaRole: "status",
    ariaLive: "polite",
    tags: ["pricing", "chip", "outline", "commerce"],
  },
  {
    id: "signal-orb",
    name: "Signal Orb",
    label: "1",
    description: "Orb-like badge with rich motion and high contrast.",
    variant: "neumorphic",
    shape: "circle",
    iconName: "zap",
    iconPosition: "only",
    showIcon: true,
    showDot: false,
    dismissible: false,
    interactive: true,
    hoverScale: 1.06,
    clickRipple: true,
    gradientEnabled: true,
    dropShadow: true,
    use3D: true,
    tiltEnabled: true,
    icon3DEnabled: true,
    icon3DGeometry: "pyramid",
    icon3DSpinSpeed: 1.5,
    ariaRole: "alert",
    ariaLive: "assertive",
    tags: ["orb", "signal", "motion", "high-contrast"],
  },
];

const BADGE_SIZES: BadgeSizeProfile[] = [
  {
    id: "compact",
    name: "Compact",
    badgeSize: "sm",
    paddingX: 10,
    paddingY: 3,
    fontSize: 12,
    borderRadius: 10,
    borderWidth: 1,
    iconGap: 4,
    iconSize: 88,
    shadowBlur: 12,
    depth: 6,
    tiltMax: 10,
    glareOpacity: 0.28,
    labelCount: "",
  },
  {
    id: "balanced",
    name: "Balanced",
    badgeSize: "md",
    paddingX: 12,
    paddingY: 4,
    fontSize: 14,
    borderRadius: 9999,
    borderWidth: 1,
    iconGap: 6,
    iconSize: 100,
    shadowBlur: 18,
    depth: 10,
    tiltMax: 14,
    glareOpacity: 0.34,
    labelCount: "3",
  },
  {
    id: "hero",
    name: "Hero",
    badgeSize: "lg",
    paddingX: 16,
    paddingY: 6,
    fontSize: 15,
    borderRadius: 9999,
    borderWidth: 1.5,
    iconGap: 8,
    iconSize: 112,
    shadowBlur: 24,
    depth: 14,
    tiltMax: 18,
    glareOpacity: 0.42,
    labelCount: "99+",
  },
];

function buildBadgePreset(
  theme: BadgeTheme,
  archetype: BadgeArchetype,
  size: BadgeSizeProfile,
): BadgePreset {
  const label = archetype.label;
  const state: Partial<BadgeState> = {
    ...INITIAL_BADGE_STATE,
    label,
    count: archetype.label === "Alerts" ? size.labelCount || "3" : archetype.label === "Orders" ? "24" : "",
    showIcon: archetype.showIcon,
    iconName: archetype.iconName,
    iconPosition: archetype.iconPosition,
    iconGap: size.iconGap,
    iconSize: size.iconSize,
    variant: archetype.variant,
    shape: archetype.shape,
    size: size.badgeSize,
    color: theme.color,
    textColor: theme.textColor,
    paddingX: size.paddingX,
    paddingY: size.paddingY,
    fontSize: size.fontSize,
    borderRadius: size.borderRadius,
    borderWidth: size.borderWidth,
    showDot: archetype.showDot,
    dotColor: theme.dotColor,
    dotPulse: archetype.showDot,
    gradientEnabled: archetype.gradientEnabled,
    gradientStart: theme.gradientStart,
    gradientEnd: theme.gradientEnd,
    gradientAngle: archetype.variant === "glass" ? 135 : archetype.variant === "solid" ? 120 : 45,
    dropShadow: archetype.dropShadow,
    shadowColor: theme.shadowColor,
    shadowBlur: size.shadowBlur,
    use3D: archetype.use3D,
    depth: size.depth,
    tiltEnabled: archetype.tiltEnabled,
    tiltMax: size.tiltMax,
    glareOpacity: size.glareOpacity,
    icon3DEnabled: archetype.icon3DEnabled,
    icon3DGeometry: archetype.icon3DGeometry,
    icon3DSpinSpeed: archetype.icon3DSpinSpeed,
    dismissible: archetype.dismissible,
    interactive: archetype.interactive,
    hoverScale: archetype.hoverScale,
    clickRipple: archetype.clickRipple,
    ariaLabel: `${theme.name} ${archetype.name} badge`,
    ariaRole: archetype.ariaRole,
    ariaLive: archetype.ariaLive,
  };

  return {
    id: `${theme.id}-${archetype.id}-${size.id}`,
    name: `${theme.name} ${archetype.name} ${size.name}`,
    description: `${archetype.description} using the ${theme.name} palette.`,
    tags: [...new Set([theme.id, theme.name, archetype.id, archetype.name, size.id, size.name, ...archetype.tags])],
    family: theme.name,
    archetype: archetype.name,
    size: size.name,
    state,
  };
}

export const BADGE_PRESETS: BadgePreset[] = BADGE_THEMES.flatMap((theme) =>
  BADGE_ARCHETYPES.flatMap((archetype) =>
    BADGE_SIZES.map((size) => buildBadgePreset(theme, archetype, size)),
  ),
);

export const BADGE_PRESET_COUNT = BADGE_PRESETS.length;
